@startuml

class Main
class Account
class Checkout
class DbIO
class FileIO
class JsonParser
class MainMenu
class MenuCard
class Payment
class Searcher
class StartMenu
class TextUI
interface Menu

Main --* Account
Main --* Checkout
Main --* DbIO
Main --* TextUI
Main --* FileIO
Main --* MenuCard
Main --* Payment
Main --* Searcher
Main --* JsonParser

Main : + public static void main(String[] args)
Main : + private static Account currentAccount;
Main : + public static void setCurrentAccount(Account currentAccount)

Menu <|-- StartMenu
Menu <|-- MainMenu

StartMenu : + public void showMenu();
StartMenu : + public void goBack();

Account : + private Account(String userName, String password)
Account : + public Account(String userName, String password, String email, int id)
Account : + public static void AddAccountToList(Account a)

Account : + public static Account register(String username, String password)
Account : + public static Account register()
Account : + public static Account login()
Account : + private boolean tryLogin(String username, String password);
Account : + public int getSQLID();
Account : + Boolean isGuest
Account : + String userName
Account : + String password
Account : + String email
Account : + private int SQLID
Account : + private static ArrayList<Account> accounts = new ArrayList<>();

TextUI : + public static consumeLine()
TextUI : + public static void sendMessage(String text)
TextUI : + public static void sendMultipleMessages(String[] lines)
TextUI : + public static void endObjectAsMessage(Object obj)
TextUI : + public static String getUserInput(String text)

Menu : + public void goBack();
Menu : + public void showMenu();

DbIO : + public void setup();
DbIO : + public void saveAccountData();
DbIO : + public void establishConnection();
DbIO : + private ArrayList<Account>();
DbIO : + private ArrayList<MenuCard> loadMenuCardData();

FileIO : + scanner.File()
FileIO : + readDataLines(String path)
FileIO : + public String[] getLinesFromFile(String path);
FileIO : + public String getTextFromFile(String path);
FileIO : + public void setup();

TextUI : + public static void sendMessage(String text)

MenuCard : + public void showCatalogue(Account account);

Searcher : + public boolean checkForDB();
Searcher : + public searchCity();

Checkout : + public checkoutMessage();

Payment : + public boolean creditCardInfo();

MainMenu : + public void goBack();
MainMenu : + public void showMenu();







@enduml